# Generated by Django 3.2.13 on 2022-06-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220612_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.aluno'),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[['PRAZO', 'PRAZO'], ['À VISTA', 'A_VISTA']], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ManyToManyField(to='core.Produto'),
        ),
    ]
