# Generated by Django 3.2.13 on 2022-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220617_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='nome',
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[['PRAZO', 'PRAZO'], ['À VISTA', 'À VISTA']], max_length=255),
        ),
    ]
