# Generated by Django 3.2.13 on 2022-06-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_venda_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='dia_semana',
            field=models.CharField(default='Seg', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='hora_fim',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='hora_inicio',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profissional'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.localatividade'),
            preserve_default=False,
        ),
    ]
