# Generated by Django 3.2.13 on 2022-06-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220617_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.atividade')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.matricula')),
            ],
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
    ]
